version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "trafficCars"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    ports:
      - "9100:5432"